# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: SWIN-GoPro-width32
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 42

datasets:
  train:
    name: real-train
    type: PairedImageDataset
    dataroot_gt: ./datasets/realdata/train/label
    dataroot_lq: ./datasets/realdata/train/low

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 32
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: real-test
    type: PairedImageDataset
    dataroot_gt: ./datasets/realdata/test/label
    dataroot_lq: ./datasets/realdata/test/low
    io_backend:
      type: disk


network_g:
  type: SwinIR
  window_size: 8
  upscale: 1
  depths: [3, 3]
  embed_dim: 60
  num_heads: [3,3]
  mlp_ratio: 2
  upsampler: 'pixelshuffledirect'



# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 100000
    eta_min: !!float 1e-7

  total_iter: 100000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 4e3
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
